### ISSUE TITLE
这个命令是不是可以提供一个cli快捷命令呢

### ISSUE THREAD

**Issue by jerexyz** [gucong3000/FELS#7]
node /Users/jere/jumei/FELS/node_modules/.gulp@4.0.0-alpha.2/bin/gulp.js --gulpfile /Users/jere/jumei/FELS/gulpfile.js precommit --base /Users/jere/jumei/projects/newPartner --gui --color

**Comment by gucong3000** [comment]
快捷命令：
`hg commit`
或者
`git commit`
